const getFullName = (countryCode: string) => {
  const countryNames: Record<string, string> = {
    NED: 'Netherlands',
    USA: 'United States',
    GBR: 'United Kingdom',
    FRA: 'France',
    MEX: 'Mexico',
    ESP: 'Spain',
    MON: 'Monaco',
    CAN: 'Canada',
    DEN: 'Denmark',
    JPN: 'Japan',
    THA: 'Thailand',
    CHN: 'China',
    NZL: 'New Zealand',
    AUS: 'Australia',
    GER: 'Germany',
    FIN: 'Finland',
    ITA: 'Italy',
    BRA: 'Brazil',
    RUS: 'Russia',
    IND: 'India',
    KOR: 'South Korea',
    SWE: 'Sweden',
    NOR: 'Norway',
    BEL: 'Belgium',
    AUT: 'Austria',
    SUI: 'Switzerland',
    POR: 'Portugal',
    ARG: 'Argentina',
    CHI: 'Chile',
    ZAF: 'South Africa',
    POL: 'Poland',
    HUN: 'Hungary',
    CZE: 'Czech Republic',
    SVK: 'Slovakia',
    IRL: 'Ireland',
    ISR: 'Israel',
    TUR: 'Turkey',
    GRE: 'Greece',
    UAE: 'United Arab Emirates',
    QAT: 'Qatar',
    EGY: 'Egypt',
    NGA: 'Nigeria',
    KEN: 'Kenya',
    MAR: 'Morocco',
    PER: 'Peru',
    COL: 'Colombia',
    VEN: 'Venezuela',
    URY: 'Uruguay',
    PRY: 'Paraguay',
    BOL: 'Bolivia',
    ECU: 'Ecuador',
    CUB: 'Cuba',
    DOM: 'Dominican Republic',
    PHL: 'Philippines',
    VNM: 'Vietnam',
    PAK: 'Pakistan',
    BGD: 'Bangladesh',
    LKA: 'Sri Lanka',
    NPL: 'Nepal',
    BTN: 'Bhutan',
    MDV: 'Maldives',
    ISL: 'Iceland',
    LUX: 'Luxembourg',
    MCO: 'Monaco',
    AND: 'Andorra',
    LIE: 'Liechtenstein',
    SMR: 'San Marino',
    VAT: 'Vatican City',
    MLT: 'Malta',
    CYP: 'Cyprus',
    EST: 'Estonia',
    LVA: 'Latvia',
    LTU: 'Lithuania',
    SVN: 'Slovenia',
    HRV: 'Croatia',
    BIH: 'Bosnia and Herzegovina',
    SRB: 'Serbia',
    MNE: 'Montenegro',
    MKD: 'North Macedonia',
    ALB: 'Albania',
    XKX: 'Kosovo',
    BLR: 'Belarus',
    UKR: 'Ukraine',
    GEO: 'Georgia',
    ARM: 'Armenia',
    AZE: 'Azerbaijan',
    KAZ: 'Kazakhstan',
    UZB: 'Uzbekistan',
    TKM: 'Turkmenistan',
    KGZ: 'Kyrgyzstan',
    TJK: 'Tajikistan',
    MNG: 'Mongolia',
    AFG: 'Afghanistan',
    IRN: 'Iran',
    IRQ: 'Iraq',
    SYR: 'Syria',
    LBN: 'Lebanon',
    JOR: 'Jordan',
    PSE: 'Palestine',
    YEM: 'Yemen',
    OMN: 'Oman',
    BHR: 'Bahrain',
    KWT: 'Kuwait',
    LBY: 'Libya',
    SDN: 'Sudan',
    ETH: 'Ethiopia',
    SOM: 'Somalia',
    UGA: 'Uganda',
    TZA: 'Tanzania',
    ZWE: 'Zimbabwe',
    ZMB: 'Zambia',
    BWA: 'Botswana',
    NAM: 'Namibia',
    AGO: 'Angola',
    MOZ: 'Mozambique',
    MDG: 'Madagascar',
    SYC: 'Seychelles',
    MUS: 'Mauritius',
    FJI: 'Fiji',
    PNG: 'Papua New Guinea',
    WSM: 'Samoa',
    TON: 'Tonga',
    VUT: 'Vanuatu',
    SLB: 'Solomon Islands',
    KIR: 'Kiribati',
    FSM: 'Micronesia',
    MHL: 'Marshall Islands',
    PLW: 'Palau',
    NRU: 'Nauru',
    TUV: 'Tuvalu',
  };
  return countryNames[countryCode] || 'Unknown Country';
};

export const getCountryFullName = (countryCode: string): string => {
  const code = countryCode.toUpperCase();
  return getFullName(code);
};
